[package]
name = "screen_reader_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocrs = { git = "https://github.com/robertknight/ocrs.git" }
screenshots = "*"
rten = "*"
rten-imageproc = "*"
mouse_position = "*"
glium = { version = "*", default-features = true }
imgui = "*"
imgui-glium-renderer = "*"
imgui-winit-support = "*"
winit = "*"
tts = "*"

[target.'cfg(windows)'.dependencies]
native-windows-gui = "*"
native-windows-derive = "*" # Optional. Only if the derive macro is used.
windows = { version = "*", features = [ "Win32_UI", "Win32_UI_WindowsAndMessaging" ] }
winapi = "*"

[build-dependencies]
embed-manifest = "*"