[package]
name = "screen_reader_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocrs = { git = "https://github.com/robertknight/ocrs.git" }
image = {version = "*", features=["bmp"]}
xcap = "*"
rten = "*"
rten-imageproc = "*"
mouse_position = "*"
tts = "*"
iced = { path = "../iced", features = ["advanced", "image"] }

[target.'cfg(windows)'.dependencies]
native-windows-gui = { path = "../native-windows-gui/native-windows-gui", features = ["image-decoder"]}
native-windows-derive = { path = "../native-windows-gui/native-windows-derive" }
windows = { version = "*", features = [ "Win32_UI", "Win32_UI_WindowsAndMessaging" ] }
winapi = "*"

[build-dependencies]
embed-manifest = "*"